language: generic
services:
  - docker
before_install:
  - time docker pull openmodelica/openmodelica:v1.12.0-minimal
  - time docker pull openmodelica/moparser:xenial
script:
  - docker run -v "$PWD/$PWD" openmodelica/openmodelica:v1.12.0-minimal ls
  - docker run -v "$PWD/$PWD" openmodelica/openmodelica:v1.12.0-minimal omc check.mos
  - docker run -v "$PWD/$PWD" openmodelica/moparser:xenial moparser -r -v 2.2 BioChem
