language: generic
services:
  - docker
before_install:
  - time docker pull openmodelica/openmodelica:v1.12.0-minimal
  - time docker pull openmodelica/moparser:xenial
script:
  - docker run openmodelica/openmodelica:v1.12.0-minimal omc check.mos
  - docker run openmodelica/moparser moparser -r -v 2.2 BioChem
